### ISSUE TITLE
ServerChatEvent

### ISSUE THREAD

**Issue by JoeSchmo2840** [Volition21/BlockTrackR#2]
[21:18:47] [Server thread/ERROR] [Sponge]: Could not pass ServerChatEvent to SpongePlugin:BlockTrackR{1.0}
java.lang.NoSuchMethodError: org.spongepowered.api.event.entity.player.PlayerChatEvent.getPlayer()Lorg/spongepowered/api/entity/player/Player;
        at com.Volition21.BlockTrackR.Event.BTRAsyncPlayerChatEvent.AsyncPlayerChatEvent(BTRAsyncPlayerChatEvent.java:49) ~[BTRAsyncPlayerChatEvent.class:?]
        at org.spongepowered.common.event.handler.PlayerChatEventHandler_BTRAsyncPlayerChatEvent_AsyncPlayerChatEvent33.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredHandler.handle(RegisteredHandler.java:86) ~[RegisteredHandler.class:1.8-1371-2.1DEV-467+unknown-b467.git-unknown]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:248) [SpongeEventManager.class:1.8-1371-2.1DEV-467+unknown-b467.git-unknown]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:82) [SpongeModEventManager.class:1.8-1371-2.1DEV-467+unknown-b467.git-unknown]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:56) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.java:431) [ForgeHooks.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:796) [rj.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:709) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by JoeSchmo2840** [comment]
Im also using ExtraChat https://forums.spongepowered.org/t/extrachat-giving-your-chat-some-life-v1-4c-chat-channels-and-community-word-blacklist/6877

**Comment by Volition21** [comment]
Can't replicate the issue on SpongeDEV-514 and ExtraChat-1.4e. This error looks like it came from BlockTrackR relying on outdated dependencies.

As of the time of writing, BlockTrackR appears to have no compatibility issues with ExtraChat-1.4e on SpongeDEV-514.
